[project]
name = "agent-forecaster"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.0.0",
    "fastapi>=0.115.12",
    "mcp>=1.9.2",
    "requests>=2.32.3",
    "docker>=7.1.0",
]
